modLoader = "javafml"
loaderVersion = "[${forge_version},)"
#issueTrackerURL = ""
license = "GNU GPLv3"

[[mods]]
modId = "extendedbogeys"
version = "${version}"
displayName = "Example Mod"
authors = "Rabbitminers, RailFanNate, Keanes2, Matt, kurocat471"
description = '''
An addon mod to Create adding new styles of bogey and an interface for other mods to do so
'''

# TODO:
logoFile = "icon.png"

[[dependencies.extendedbogeys]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extendedbogeys]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.extendedbogeys]]
modId="create"
mandatory=true
versionRange="${create_version}"
ordering="NONE"
side="BOTH"